### ISSUE TITLE
mbstring not installed in /var/www/hcard.geekhood.net/class/controller.php:21

### ISSUE THREAD

**Issue by jonasjacek** [pornel/hCardValidator#7]
Hi, 
just wanted to inform you, that there is an error at http://hcard.geekhood.net/:

> Internal Error
> 
> Because of an error in the validator it was impossible to check this document.
> 
> Exception: mbstring not installed in /var/www/hcard.geekhood.net/class/controller.php:21
> Stack trace:
> #0 /var/www/hcard.geekhood.net/class/controller.php(7): Controller->initPHP(false)
> #1 /var/www/hcard.geekhood.net/index.php(17): Controller->init(false)
> #2 {main}

**Comment by pornel** [comment]
Fixed, thanks.
